#pragma once

#define INET_FORTH_VERSION "0.1.0"

#define NODE_MAX_ARITY 16
#define NODE_ALLOCATOR_BATCH_SIZE 1024
#define NODE_ALLOCATOR_CACHE_SIZE (64 * 1024)
#define WORKER_TASK_QUEUE_SIZE (1024 * 1024)

#define DEBUG_TASK_MUTEX 0
#define DEBUG_TASK_LOG 0
#define DEBUG_NODE_MUTEX 1
#define DEBUG_NODE_ALLOCATOR_DISABLED 0
#define DEBUG_WORK_STEALING_DISABLED 0
#define DEBUG_STEP_LOG 0

extern bool single_threaded_flag;
